# controller.config.yaml

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    axis_angular:
      yaw: 0
    scale_linear:
      x: 2.0
    scale_angular:
      yaw: 2.0
    enable_button: -1 # (disabled) "enable" button, press to input ANY buttons.
    require_enable_button: False # default: True