/controller_interpreter:
  ros__parameters:
    axis_angular:
      pitch: -1
      roll: -1
      yaw: 0
    axis_linear:
      x: 1
      y: -1
      z: -1
    enable_button: 5
    enable_turbo_button: -1
    frame: teleop_twist_joy
    inverted_reverse: false
    publish_stamped_twist: false
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    require_enable_button: false
    scale_angular:
      pitch: 0.0
      roll: 0.0
      yaw: 1.0
    scale_angular_turbo:
      pitch: 0.0
      roll: 0.0
      yaw: 1.0
    scale_linear:
      x: 1.0
      y: 0.0
      z: 0.0
    scale_linear_turbo:
      x: 1.0
      y: 0.0
      z: 0.0
    start_type_description_service: true
    use_sim_time: false

